apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: health-check-operator
    app.kubernetes.io/part-of: health-check-operator
    app.kubernetes.io/managed-by: kustomize
  name: proxy-rolebinding
  namespace: health-check-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxy-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
