apiVersion: v1
kind: Secret
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: health-check-operator
    app.kubernetes.io/part-of: health-check-operator
    app.kubernetes.io/managed-by: kustomize
  name: quay-secret
  namespace: system
data:
  .dockerconfigjson: ""
type: kubernetes.io/dockerconfigjson
