kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ .Values.webappData.serviceAccount.roleBinding }}
    namespace: {{ .Release.Namespace }}
subjects:
    - kind: ServiceAccount
      name: {{ .Values.webappData.serviceAccount.name }}
      namespace: {{ .Values.webappData.namespace }}
roleRef:
    kind: Role
    name: {{ .Values.webappData.serviceAccount.role }}
    apiGroup: rbac.authorization.k8s.io