apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.kafkaData.imagePullSecretName . }}
  namespace: {{ .Values.kafkaData.namespace }}
data:
  .dockerconfigjson: {{ .Values.secret.data.dockerconfigjson }}
type: {{ .Values.secret.type }}