apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.kafkaData.deploymentName . }}
  namespace: {{ .Values.kafkaData.namespace }}
  labels:
    app.kubernetes.io/name: {{ tpl .Values.kafkaData.deploymentName . }}
    app.kubernetes.io/affinity: {{ .Values.affinity.consumerName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ tpl .Values.kafkaData.deploymentName . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ tpl .Values.kafkaData.deploymentName . }}
        app.kubernetes.io/affinity: {{ .Values.affinity.consumerName }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/affinity: {{ .Values.affinity.consumerName }}
            topologyKey: "topology.kubernetes.io/zone"
      serviceAccountName: {{ .Values.kafkaData.serviceAccountName }}
      initContainers:
        - name: postgres-password
          image: {{ .Values.initPostgresPassword.image }}
          resources:
            requests:
              memory: {{ .Values.initPostgresPassword.resources.requests.memory }}
              cpu: {{ .Values.initPostgresPassword.resources.requests.cpu }}
            limits:
              memory: {{ .Values.initPostgresPassword.resources.limits.memory }}
              cpu: {{ .Values.initPostgresPassword.resources.limits.cpu }}
          envFrom:
            - configMapRef:
                name: {{ tpl .Values.kafkaData.configMapName . }}
          command: ['/bin/sh', '-c', 'kubectl delete secret $SECRET_NAME -n $DEST_NAMESPACE --ignore-not-found && kubectl get secrets $SECRET_NAME -n $DB_NAMESPACE -o yaml | sed s/"namespace: $DB_NAMESPACE"/"namespace: $DEST_NAMESPACE"/ | kubectl apply -n $DEST_NAMESPACE -f -']

        - name: check-db-ready
          image: {{ .Values.initCheckDbConnection.image }}
          resources:
            requests:
              memory: {{ .Values.initCheckDbConnection.resources.requests.memory }}
              cpu: {{ .Values.initCheckDbConnection.resources.requests.cpu }}
            limits:
              memory: {{ .Values.initCheckDbConnection.resources.limits.memory }}
              cpu: {{ .Values.initCheckDbConnection.resources.limits.cpu }}
          envFrom:
            - configMapRef:
                name: {{ tpl .Values.kafkaData.configMapName . }}
          command: ['sh', '-c',
            'until pg_isready -h $DB_HOST -p $DB_PORT; 
            do echo waiting for database; sleep 2; done;']


      containers:
        - name: http-check-result
          image: {{ .Values.consumer.image }}
          resources:
            requests:
              memory: {{ .Values.consumer.resources.requests.memory }}
              cpu: {{ .Values.consumer.resources.requests.cpu }}
            limits:
              memory: {{ .Values.consumer.resources.limits.memory }}
              cpu: {{ .Values.consumer.resources.limits.cpu }}
          envFrom:
            - configMapRef:
                name: {{ tpl .Values.kafkaData.configMapName . }}
          env:
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ tpl .Values.kafkaData.secretName . }}
                    key: postgres-password


      imagePullSecrets:
        - name: {{ tpl .Values.kafkaData.imagePullSecretName . }}

  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
