apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.istio.virtualService.name }}
  namespace: {{ .Values.webappData.namespace }}
spec:
  hosts:
  - {{ .Values.istio.webappHost }}
  gateways:
  - {{ .Values.istio.gatewayNamespace }}/{{ .Values.istio.gatewayName }}
  tcp:
  - match:
    - port: {{ .Values.istio.virtualService.portNumber }}
    route:
    - destination:
        port:
          number: {{ .Values.istio.virtualService.portNumber }}
        host: {{ .Values.webappData.serviceName }}
