kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ .Values.webappData.roleBinding }}
    namespace: {{ .Values.webappData.namespace }}
subjects:
    - kind: ServiceAccount
      name: {{ .Values.webappData.serviceAccountName }}
      namespace: {{ .Values.webappData.namespace }}
roleRef:
    kind: Role
    name: {{ .Values.webappData.role }}
    apiGroup: rbac.authorization.k8s.io