apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpa.webappName }}
  namespace: {{ .Values.hpa.webappNamespace }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.averageCPUUtilization }}
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: {{ .Values.hpa.scaleUp.podValue }}
          periodSeconds:  {{ .Values.hpa.scaleUp.periodSeconds }}
      stabilizationWindowSeconds: {{ .Values.hpa.scaleUp.stabilizationWindowSeconds }}
    scaleDown:
      policies:
        - type: Pods
          value: {{ .Values.hpa.scaleDown.podValue }}
          periodSeconds: {{ .Values.hpa.scaleDown.periodSeconds }}
      stabilizationWindowSeconds: {{ .Values.hpa.scaleDown.stabilizationWindowSeconds }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ tpl .Values.webappData.deploymentName . }}