apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.kafkaRoleBindingName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.kafkaRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.consumer.serviceAccountName }}
  namespace: {{ .Values.consumer.namespace }}
- kind: ServiceAccount
  name: {{ .Values.operator.serviceAccountName }}
  namespace: {{ .Values.operator.namespace }}
